"""add provider payment id to payments

Revision ID: 3f39cbc84de1
Revises: c2f82f152b06
Create Date: 2026-09-05 01:20:18.186416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f39cbc84de1'
down_revision: Union[str, Sequence[str], None] = 'c2f82f152b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_payment_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_column('payments', 'provider_payment_id')
    # ### end Alembic commands ###
