"""create idempotency table

Revision ID: 4bba8b572627
Revises: 93c9427895d8
Create Date: 2026-08-09 01:37:10.796022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4bba8b572627'
down_revision: Union[str, Sequence[str], None] = '93c9427895d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ),
    sa.PrimaryKeyConstraint('idempotency_key_id'),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_merchant_idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_keys_merchant_id'), 'idempotency_keys', ['merchant_id'], unique=False)
    # ensure enum type exists (no-op if already present)
    paymentstatus = postgresql.ENUM('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus')
    paymentstatus.create(op.get_bind(), checkfirst=True)

    op.create_table('payment_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('old_state', postgresql.ENUM('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus', create_type=False), nullable=False),
    sa.Column('new_state', postgresql.ENUM('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus', create_type=False), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_payment_history_payment_id'), 'payment_history', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_history_payment_id'), table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_idempotency_keys_merchant_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
