"""add payment_id to idempotency keys

Revision ID: 5c95868312dd
Revises: a1b2c3d4e5f6
Create Date: 2026-08-13 00:09:07.863303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c95868312dd'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('payment_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_idempotency_keys_payment_id'), 'idempotency_keys', ['payment_id'], unique=False)
    op.create_foreign_key(None, 'idempotency_keys', 'payments', ['payment_id'], ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idempotency_keys', type_='foreignkey')
    op.drop_index(op.f('ix_idempotency_keys_payment_id'), table_name='idempotency_keys')
    op.drop_column('idempotency_keys', 'payment_id')
    # ### end Alembic commands ###
