"""create payment_history  table

Revision ID: 93c9427895d8
Revises: 34b9aa1ef579
Create Date: 2026-08-09 00:13:42.857222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c9427895d8'
down_revision: Union[str, Sequence[str], None] = '34b9aa1ef579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('old_state', sa.Enum('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('new_state', sa.Enum('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_payment_history_payment_id'), 'payment_history', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_history_payment_id'), table_name='payment_history')
    op.drop_table('payment_history')
    # ### end Alembic commands ###