"""allow null old state in payment history

Revision ID: c2f82f152b06
Revises: 5c95868312dd
Create Date: 2026-08-15 01:06:21.809718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2f82f152b06'
down_revision: Union[str, Sequence[str], None] = '5c95868312dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_history', 'old_state',
               existing_type=postgresql.ENUM('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_history', 'old_state',
               existing_type=postgresql.ENUM('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus'),
               nullable=False)
    # ### end Alembic commands ###
