"""create payment table

Revision ID: c9e3a36cfce2
Revises: fc76b5d7a4c5
Create Date: 2026-08-08 02:12:47.745753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e3a36cfce2'
down_revision: Union[str, Sequence[str], None] = 'fc76b5d7a4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_payment_method_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Enum('INR', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('payment_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_payment_method_id'], ['merchant_payment_methods.merchant_payment_method_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payments_merchant_payment_method_id'), 'payments', ['merchant_payment_method_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_merchant_payment_method_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###