"""create webhook table

Revision ID: fc76b5d7a4c5
Revises: 3208c649be2e
Create Date: 2026-08-06 00:51:01.871196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc76b5d7a4c5'
down_revision: Union[str, Sequence[str], None] = '3208c649be2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('callback_url', sa.String(length=500), nullable=False),
    sa.Column('event_types', postgresql.ARRAY(sa.Enum('PAYMENT', 'REFUND', name='webhook_event_type_enum')), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ),
    sa.PrimaryKeyConstraint('webhook_id'),
    sa.UniqueConstraint('merchant_id', name='uq_webhook_merchant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhooks')
    # ### end Alembic commands ###
