"""create_provider_payments

Revision ID: a034dca0e1a0
Revises: 
Create Date: 2026-08-30 21:35:24.493084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a034dca0e1a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_payments',
    sa.Column('provider_payment_id', sa.String(length=36), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_provider_payments_gateway_payment_id'), 'provider_payments', ['gateway_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_payments_gateway_payment_id'), table_name='provider_payments')
    op.drop_table('provider_payments')
    # ### end Alembic commands ###
