"""add unique constraint on merchant api key name

Revision ID: 2935fa80143e
Revises: cf83e01451cd
Create Date: 2026-07-30 01:09:45.480514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2935fa80143e'
down_revision: Union[str, Sequence[str], None] = 'cf83e01451cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_merchant_key_name', 'api_keys', ['merchant_id', 'key_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_merchant_key_name', 'api_keys', type_='unique')
    # ### end Alembic commands ###
