"""create merchant_payment_methods table

Revision ID: 3208c649be2e
Revises: 5e578ab9ec02
Create Date: 2026-08-04 22:17:33.376600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3208c649be2e'
down_revision: Union[str, Sequence[str], None] = '5e578ab9ec02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_payment_methods',
    sa.Column('merchant_payment_method_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.payment_method_id'], ),
    sa.PrimaryKeyConstraint('merchant_payment_method_id'),
    sa.UniqueConstraint('merchant_id', 'payment_method_id', name='uq_merchant_payment_method')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_payment_methods')
    # ### end Alembic commands ###
