from enum import Enum


class PaymentScenario(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PROCESSING = "PROCESSING"
    TIMEOUT_BEFORE_CREATE = "TIMEOUT_BEFORE_CREATE"
    TIMEOUT_AFTER_CREATE = "TIMEOUT_AFTER_CREATE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    